In [201]:
import pandas as pd
import numpy as np
import datetime
from pandas_summary import DataFrameSummary
from sklearn.model_selection import train_test_split

In [202]:
def get_mean_by_column(df,column, sales_str):
    group_means_dict = {}
    group_mean_list = []
    for columna, group_df in df.groupby('movieId'):
        group_mean =  group_df['rating'].mean()
        group_means_dict['rating'] = group_mean
        group_mean_list.append(group_mean)
    print('Return:', get_metric(df['rating'],df[column].apply(group_means_dict.get)))
    return group_means_dict, group_mean_list

In [203]:
def get_metric(y, y_est):
    return np.sqrt((((y - y_est)/y)**2).sum()/len(y))

In [204]:
df_train = pd.read_feather('all_train_normalized.fth')

In [205]:
display(df_train.head())
display(DataFrameSummary(df_train).summary())

,index,userId,movieId,rating,unknown,Action,Adventure,Animation,Children,Comedy,...,War,Western,age,gender,occupation,ZipCode,Year,Month,Week,Day
0,0,1,1,5,0,0,0,1,1,1,...,0,0,24,1,19,85711,1995,1,52,1
1,1,1,2,3,0,1,1,0,0,0,...,0,0,24,1,19,85711,1995,1,52,1
2,2,1,3,4,0,0,0,0,0,0,...,0,0,24,1,19,85711,1995,1,52,1
3,3,1,4,3,0,1,0,0,0,1,...,0,0,24,1,19,85711,1995,1,52,1
4,4,1,5,3,0,0,0,0,0,0,...,0,0,24,1,19,85711,1995,1,52,1

,index,userId,movieId,rating,unknown,Action,Adventure,Animation,Children,Comedy,...,War,Western,age,gender,occupation,ZipCode,Year,Month,Week,Day
count,80000.000000,80000.00000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,...,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,NaN,80000.00000,80000.000000,80000.000000,80000.000000
mean,39999.500000,525.16570,425.177800,3.528350,0.000037,0.257075,0.139137,0.036163,0.072237,0.298700,...,0.095162,0.018500,32.826838,0.738662,11.189850,NaN,1987.96505,2.649087,28.384438,5.744338
std,23094.155105,255.94956,331.097575,1.118565,0.006124,0.437024,0.346092,0.186695,0.258882,0.457691,...,0.293441,0.134752,11.584327,0.439366,6.602159,NaN,14.16880,3.126303,22.859162,8.377624
min,0.000000,1.00000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.000000,0.000000,0.000000,NaN,1922.00000,1.000000,1.000000,1.000000
25%,19999.750000,334.00000,175.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,24.000000,0.000000,4.000000,NaN,1986.00000,1.000000,1.000000,1.000000
50%,39999.500000,535.00000,321.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,30.000000,1.000000,13.000000,NaN,1994.00000,1.000000,31.000000,1.000000
75%,59999.250000,744.00000,629.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,40.000000,1.000000,18.000000,NaN,1996.00000,3.000000,52.000000,8.000000
max,79999.000000,943.00000,1682.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,73.000000,1.000000,20.000000,NaN,1998.00000,12.000000,53.000000,31.000000
counts,80000,80000,80000,80000,80000,80000,80000,80000,80000,80000,...,80000,80000,80000,80000,80000,80000,80000,80000,80000,80000
uniques,80000,943,1633,5,2,2,2,2,2,2,...,2,2,61,2,21,795,71,12,53,31
missing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
missing_perc,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,...,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%
types,numeric,numeric,numeric,numeric,bool,bool,bool,bool,bool,bool,...,bool,bool,numeric,bool,numeric,categorical,numeric,numeric,numeric,numeric

In [206]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        80000 non-null  int64
 1   userId       80000 non-null  int64
 2   movieId      80000 non-null  int64
 3   rating       80000 non-null  int64
 4   unknown      80000 non-null  int64
 5   Action       80000 non-null  int64
 6   Adventure    80000 non-null  int64
 7   Animation    80000 non-null  int64
 8   Children     80000 non-null  int64
 9   Comedy       80000 non-null  int64
 10  Crime        80000 non-null  int64
 11  Documentary  80000 non-null  int64
 12  Drama        80000 non-null  int64
 13  Fantasy      80000 non-null  int64
 14  Film-Noir    80000 non-null  int64
 15  Horror       80000 non-null  int64
 16  Musical      80000 non-null  int64
 17  Mystery      80000 non-null  int64
 18  Romance      80000 non-null  int64
 19  Sci-Fi       80000 non-null  int64
 20  Thriller     80000 non-null  int64
 21  War          80000 non-null  int64
 22  Western      80000 non-null  int64
 23  age          80000 non-null  int64
 24  gender       80000 non-null  int64
 25  occupation   80000 non-null  int64
 26  ZipCode      80000 non-null  object
 27  Year         80000 non-null  int64
 28  Month        80000 non-null  int64
 29  Week         80000 non-null  int64
 30  Day          80000 non-null  int64
dtypes: int64(30), object(1)
memory usage: 18.9+ MB

In [207]:
df_train.columns

Index(['index', 'userId', 'movieId', 'rating', 'unknown', 'Action',
       'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary',
       'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western', 'age', 'gender',
       'occupation', 'ZipCode', 'Year', 'Month', 'Week', 'Day'],
      dtype='object')

In [208]:
X = df_train[['userId','movieId','unknown', 'Action',
       'Adventure', 'Animation', 'Children', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western', 'age',
       'gender', 'occupation', 'ZipCode', 'Year', 'Month', 'Week', 'Day']]
y = df_train['rating']

In [209]:
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=2000)

In [196]:
X_train

,userId,movieId,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,War,Western,age,gender,occupation,zip code,Year,Month,Week,Day
41006,540,117,0,1,1,0,0,0,0,0,...,0,0,28,1,4,91201,1996,6,23,7
64174,788,519,0,0,1,0,0,0,0,0,...,0,0,51,1,0,05779,1948,1,1,1
46456,603,12,0,0,0,0,0,0,1,0,...,0,0,21,1,14,47905,1995,8,33,14
33328,472,271,0,1,1,0,0,0,0,0,...,1,0,24,1,18,87544,1997,1,1,1
73918,886,87,0,0,0,0,0,0,0,0,...,0,0,20,1,18,61820,1993,1,53,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58177,716,650,0,0,0,0,0,0,0,0,...,0,0,36,0,0,44265,1957,1,1,1
24325,393,58,0,0,0,0,0,0,0,0,...,0,0,19,1,18,83686,1994,1,52,1
42746,557,8,0,0,0,0,1,1,0,0,...,0,0,30,0,20,11217,1995,1,52,1
79379,936,815,0,0,0,0,0,0,0,0,...,0,0,24,1,13,32789,1996,11,48,30
37324,505,161,0,1,0,0,0,0,0,0,...,0,0,27,0,13,20657,1986,1,1,1

In [158]:
from tensorflow.keras.utils import to_categorical
from matplotlib import pyplot as plt
from tensorflow.keras.callbacks import ModelCheckpoint 
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Input, Concatenate
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras import optimizers
from tensorflow.keras import initializers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras import backend as K

In [141]:
def rmspe(y_true, y_pred):
    return K.sqrt(K.mean(K.square((y_true - y_pred)/y_true)))

In [108]:
hidden_units = 10
model = Sequential()
model.add(Dense(hidden_units, input_shape=(2,), name='Salida'))
model.add(Dense(1, activation='linear'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
Salida (Dense)               (None, 10)                30
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11
=================================================================
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________

In [110]:
epochs = 100
model.compile(
    Adam(lr=0.1),
    loss='mse',
    metrics=[
        RootMeanSquaredError('rmse')
    ])

model.fit(X_train,y_train, epochs=epochs, batch_size=128)

Epoch 1/100
610/610 [==============================] - 0s 420us/step - loss: 199.2068 - rmse: 14.1141
Epoch 2/100
610/610 [==============================] - 0s 459us/step - loss: 1.4354 - rmse: 1.1981
Epoch 3/100
610/610 [==============================] - 0s 423us/step - loss: 1.3088 - rmse: 1.1440
Epoch 4/100
610/610 [==============================] - 0s 413us/step - loss: 1.4020 - rmse: 1.1841
Epoch 5/100
610/610 [==============================] - 0s 422us/step - loss: 1.4019 - rmse: 1.1840
Epoch 6/100
610/610 [==============================] - 0s 416us/step - loss: 1.3639 - rmse: 1.1678
Epoch 7/100
610/610 [==============================] - 0s 430us/step - loss: 1.3648 - rmse: 1.1682
Epoch 8/100
610/610 [==============================] - 0s 417us/step - loss: 1.2784 - rmse: 1.1307
Epoch 9/100
610/610 [==============================] - 0s 448us/step - loss: 1.2493 - rmse: 1.1177
Epoch 10/100
610/610 [==============================] - 0s 449us/step - loss: 1.2196 - rmse: 1.1044
Epoch 11/100
610/610 [==============================] - 0s 418us/step - loss: 1.2141 - rmse: 1.1019
Epoch 12/100
610/610 [==============================] - 0s 431us/step - loss: 1.2134 - rmse: 1.1016
Epoch 13/100
610/610 [==============================] - 0s 418us/step - loss: 1.2154 - rmse: 1.1025
Epoch 14/100
610/610 [==============================] - 0s 419us/step - loss: 1.2179 - rmse: 1.1036
Epoch 15/100
610/610 [==============================] - 0s 420us/step - loss: 1.2288 - rmse: 1.1085
Epoch 16/100
610/610 [==============================] - 0s 423us/step - loss: 1.2313 - rmse: 1.1097
Epoch 17/100
610/610 [==============================] - 0s 417us/step - loss: 6685.2988 - rmse: 81.7637
Epoch 18/100
610/610 [==============================] - 0s 421us/step - loss: 1.2315 - rmse: 1.1097
Epoch 19/100
610/610 [==============================] - 0s 418us/step - loss: 1.2253 - rmse: 1.1070
Epoch 20/100
610/610 [==============================] - 0s 420us/step - loss: 1.2230 - rmse: 1.1059
Epoch 21/100
610/610 [==============================] - 0s 425us/step - loss: 1.2268 - rmse: 1.1076
Epoch 22/100
610/610 [==============================] - 0s 416us/step - loss: 1.2415 - rmse: 1.1142
Epoch 23/100
610/610 [==============================] - 0s 414us/step - loss: 1.2395 - rmse: 1.1133
Epoch 24/100
610/610 [==============================] - 0s 421us/step - loss: 1.2468 - rmse: 1.1166
Epoch 25/100
610/610 [==============================] - 0s 415us/step - loss: 1.2525 - rmse: 1.1191
Epoch 26/100
610/610 [==============================] - 0s 424us/step - loss: 1.2968 - rmse: 1.1388
Epoch 27/100
610/610 [==============================] - 0s 420us/step - loss: 1.3828 - rmse: 1.1759
Epoch 28/100
610/610 [==============================] - 0s 426us/step - loss: 1.3699 - rmse: 1.1704
Epoch 29/100
610/610 [==============================] - 0s 413us/step - loss: 1.3847 - rmse: 1.1767
Epoch 30/100
610/610 [==============================] - 0s 417us/step - loss: 1.3686 - rmse: 1.1699
Epoch 31/100
610/610 [==============================] - 0s 428us/step - loss: 1.3151 - rmse: 1.1468
Epoch 32/100
610/610 [==============================] - 0s 426us/step - loss: 1.2480 - rmse: 1.1171
Epoch 33/100
610/610 [==============================] - 0s 445us/step - loss: 1.2232 - rmse: 1.1060
Epoch 34/100
610/610 [==============================] - 0s 440us/step - loss: 1.2175 - rmse: 1.1034
Epoch 35/100
610/610 [==============================] - 0s 447us/step - loss: 1.2143 - rmse: 1.1020
Epoch 36/100
610/610 [==============================] - 0s 422us/step - loss: 1.2147 - rmse: 1.1021
Epoch 37/100
610/610 [==============================] - 0s 415us/step - loss: 1.2165 - rmse: 1.1030
Epoch 38/100
610/610 [==============================] - 0s 422us/step - loss: 1.2200 - rmse: 1.1046
Epoch 39/100
610/610 [==============================] - 0s 423us/step - loss: 1.2231 - rmse: 1.1059
Epoch 40/100
610/610 [==============================] - 0s 416us/step - loss: 1.2443 - rmse: 1.1155
Epoch 41/100
610/610 [==============================] - 0s 427us/step - loss: 1.2530 - rmse: 1.1194
Epoch 42/100
610/610 [==============================] - 0s 426us/step - loss: 4815.0122 - rmse: 69.3903
Epoch 43/100
610/610 [==============================] - 0s 426us/step - loss: 1.6856 - rmse: 1.2983
Epoch 44/100
610/610 [==============================] - 0s 418us/step - loss: 1.4031 - rmse: 1.1845
Epoch 45/100
610/610 [==============================] - 0s 419us/step - loss: 1.2972 - rmse: 1.1389
Epoch 46/100
610/610 [==============================] - 0s 427us/step - loss: 1.2661 - rmse: 1.1252
Epoch 47/100
610/610 [==============================] - 0s 417us/step - loss: 1.3047 - rmse: 1.1422
Epoch 48/100
610/610 [==============================] - 0s 430us/step - loss: 1.3287 - rmse: 1.1527
Epoch 49/100
610/610 [==============================] - 0s 451us/step - loss: 1.3895 - rmse: 1.1788
Epoch 50/100
610/610 [==============================] - 0s 422us/step - loss: 1.6592 - rmse: 1.2881
Epoch 51/100
610/610 [==============================] - 0s 418us/step - loss: 1.5142 - rmse: 1.2305
Epoch 52/100
610/610 [==============================] - 0s 417us/step - loss: 1.5571 - rmse: 1.2478
Epoch 53/100
610/610 [==============================] - 0s 420us/step - loss: 1.3840 - rmse: 1.1764
Epoch 54/100
610/610 [==============================] - 0s 427us/step - loss: 1.3343 - rmse: 1.1551
Epoch 55/100
610/610 [==============================] - 0s 418us/step - loss: 1.2785 - rmse: 1.1307
Epoch 56/100
610/610 [==============================] - 0s 418us/step - loss: 1.2361 - rmse: 1.1118
Epoch 57/100
610/610 [==============================] - 0s 417us/step - loss: 1.2295 - rmse: 1.1088
Epoch 58/100
610/610 [==============================] - 0s 455us/step - loss: 1.2172 - rmse: 1.1033
Epoch 59/100
610/610 [==============================] - 0s 433us/step - loss: 1.2154 - rmse: 1.1025
Epoch 60/100
610/610 [==============================] - 0s 430us/step - loss: 1.2166 - rmse: 1.1030
Epoch 61/100
610/610 [==============================] - 0s 421us/step - loss: 1.2178 - rmse: 1.1035
Epoch 62/100
610/610 [==============================] - 0s 424us/step - loss: 1.2254 - rmse: 1.1070
Epoch 63/100
610/610 [==============================] - 0s 420us/step - loss: 1.2240 - rmse: 1.1064
Epoch 64/100
610/610 [==============================] - 0s 418us/step - loss: 16679.5352 - rmse: 129.1493
Epoch 65/100
610/610 [==============================] - 0s 423us/step - loss: 1.8727 - rmse: 1.3685
Epoch 66/100
610/610 [==============================] - 0s 421us/step - loss: 1.6630 - rmse: 1.2896
Epoch 67/100
610/610 [==============================] - 0s 416us/step - loss: 1.4771 - rmse: 1.2154
Epoch 68/100
610/610 [==============================] - 0s 429us/step - loss: 1.3471 - rmse: 1.1606
Epoch 69/100
610/610 [==============================] - 0s 436us/step - loss: 1.2680 - rmse: 1.1261
Epoch 70/100
610/610 [==============================] - 0s 410us/step - loss: 1.2345 - rmse: 1.1111
Epoch 71/100
610/610 [==============================] - 0s 410us/step - loss: 1.2276 - rmse: 1.1080
Epoch 72/100
610/610 [==============================] - 0s 421us/step - loss: 1.2310 - rmse: 1.1095
Epoch 73/100
610/610 [==============================] - 0s 414us/step - loss: 1.2402 - rmse: 1.1136
Epoch 74/100
610/610 [==============================] - 0s 420us/step - loss: 1.2667 - rmse: 1.1255
Epoch 75/100
610/610 [==============================] - 0s 427us/step - loss: 1.2891 - rmse: 1.1354
Epoch 76/100
610/610 [==============================] - 0s 418us/step - loss: 1.3505 - rmse: 1.1621
Epoch 77/100
610/610 [==============================] - 0s 423us/step - loss: 1.3479 - rmse: 1.1610
Epoch 78/100
610/610 [==============================] - 0s 420us/step - loss: 1.4141 - rmse: 1.1892
Epoch 79/100
610/610 [==============================] - 0s 434us/step - loss: 1.3845 - rmse: 1.1766
Epoch 80/100
610/610 [==============================] - 0s 451us/step - loss: 1.3549 - rmse: 1.1640
Epoch 81/100
610/610 [==============================] - 0s 418us/step - loss: 1.2614 - rmse: 1.1231
Epoch 82/100
610/610 [==============================] - 0s 422us/step - loss: 1.2263 - rmse: 1.1074
Epoch 83/100
610/610 [==============================] - 0s 423us/step - loss: 1.2148 - rmse: 1.1022
Epoch 84/100
610/610 [==============================] - 0s 427us/step - loss: 1.2142 - rmse: 1.1019
Epoch 85/100
610/610 [==============================] - 0s 440us/step - loss: 1.2158 - rmse: 1.1026
Epoch 86/100
610/610 [==============================] - 0s 421us/step - loss: 1.2149 - rmse: 1.1022
Epoch 87/100
610/610 [==============================] - 0s 416us/step - loss: 1.2167 - rmse: 1.1030
Epoch 88/100
610/610 [==============================] - 0s 436us/step - loss: 1.2178 - rmse: 1.1035
Epoch 89/100
610/610 [==============================] - 0s 418us/step - loss: 1.2350 - rmse: 1.1113
Epoch 90/100
610/610 [==============================] - 0s 420us/step - loss: 2566.6912 - rmse: 50.6625
Epoch 91/100
610/610 [==============================] - 0s 418us/step - loss: 4750.5239 - rmse: 68.9240
Epoch 92/100
610/610 [==============================] - 0s 436us/step - loss: 1.8062 - rmse: 1.3440
Epoch 93/100
610/610 [==============================] - 0s 431us/step - loss: 1.5382 - rmse: 1.2402
Epoch 94/100
610/610 [==============================] - 0s 428us/step - loss: 1.3572 - rmse: 1.1650
Epoch 95/100
610/610 [==============================] - 0s 419us/step - loss: 1.2694 - rmse: 1.1267
Epoch 96/100
610/610 [==============================] - 0s 435us/step - loss: 1.2334 - rmse: 1.1106
Epoch 97/100
610/610 [==============================] - 0s 425us/step - loss: 1.2400 - rmse: 1.1135
Epoch 98/100
610/610 [==============================] - 0s 428us/step - loss: 1.2495 - rmse: 1.1178
Epoch 99/100
610/610 [==============================] - 0s 431us/step - loss: 1.2674 - rmse: 1.1258
Epoch 100/100
610/610 [==============================] - 0s 421us/step - loss: 1.2974 - rmse: 1.1390

In [143]:
def get_keras_LR(X_columns, hidden_units=1):
    inputs = []
    activation = 'linear'
    if hidden_units>1:
        activation = 'relu'
    for i, col in enumerate(X_columns):
        inp = Input(shape=(X_train[i].shape[1],), name=f"{col}_input")
        inputs.append(inp)
    if len(X_columns)>1:
        concat_out = Concatenate()(inputs)
        dense_out = Dense(hidden_units, name='Dense', activation=activation)(concat_out)
    else:
        dense_out = Dense(hidden_units, name='Dense', activation=activation)(inputs[0])
    if hidden_units>1:
        dense_out = Dense(1, name='Dense_out')(dense_out)
    model = Model(inputs, dense_out)
    model.compile(optimizers.Adam(lr=0.0001), loss='mse', metrics=[rmspe, 'mse'])
    return model

In [210]:
X_columns = list(X_train.columns)
X_train = np.hsplit(X_train[X_columns].values, len(X_columns))

model = get_keras_LR(X_columns, hidden_units=20)
model.summary()

Model: "functional_11"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
userId_input (InputLayer)       [(None, 1)]          0
__________________________________________________________________________________________________
movieId_input (InputLayer)      [(None, 1)]          0
__________________________________________________________________________________________________
unknown_input (InputLayer)      [(None, 1)]          0
__________________________________________________________________________________________________
Action_input (InputLayer)       [(None, 1)]          0
__________________________________________________________________________________________________
Adventure_input (InputLayer)    [(None, 1)]          0
__________________________________________________________________________________________________
Animation_input (InputLayer)    [(None, 1)]          0
__________________________________________________________________________________________________
Children_input (InputLayer)     [(None, 1)]          0
__________________________________________________________________________________________________
Comedy_input (InputLayer)       [(None, 1)]          0
__________________________________________________________________________________________________
Crime_input (InputLayer)        [(None, 1)]          0
__________________________________________________________________________________________________
Documentary_input (InputLayer)  [(None, 1)]          0
__________________________________________________________________________________________________
Drama_input (InputLayer)        [(None, 1)]          0
__________________________________________________________________________________________________
Fantasy_input (InputLayer)      [(None, 1)]          0
__________________________________________________________________________________________________
Film-Noir_input (InputLayer)    [(None, 1)]          0
__________________________________________________________________________________________________
Horror_input (InputLayer)       [(None, 1)]          0
__________________________________________________________________________________________________
Musical_input (InputLayer)      [(None, 1)]          0
__________________________________________________________________________________________________
Mystery_input (InputLayer)      [(None, 1)]          0
__________________________________________________________________________________________________
Romance_input (InputLayer)      [(None, 1)]          0
__________________________________________________________________________________________________
Sci-Fi_input (InputLayer)       [(None, 1)]          0
__________________________________________________________________________________________________
Thriller_input (InputLayer)     [(None, 1)]          0
__________________________________________________________________________________________________
War_input (InputLayer)          [(None, 1)]          0
__________________________________________________________________________________________________
Western_input (InputLayer)      [(None, 1)]          0
__________________________________________________________________________________________________
age_input (InputLayer)          [(None, 1)]          0
__________________________________________________________________________________________________
gender_input (InputLayer)       [(None, 1)]          0
__________________________________________________________________________________________________
occupation_input (InputLayer)   [(None, 1)]          0
__________________________________________________________________________________________________
ZipCode_input (InputLayer)      [(None, 1)]          0
__________________________________________________________________________________________________
Year_input (InputLayer)         [(None, 1)]          0
__________________________________________________________________________________________________
Month_input (InputLayer)        [(None, 1)]          0
__________________________________________________________________________________________________
Week_input (InputLayer)         [(None, 1)]          0
__________________________________________________________________________________________________
Day_input (InputLayer)          [(None, 1)]          0
__________________________________________________________________________________________________
concatenate_6 (Concatenate)     (None, 29)           0           userId_input[0][0]
                                                                 movieId_input[0][0]
                                                                 unknown_input[0][0]
                                                                 Action_input[0][0]
                                                                 Adventure_input[0][0]
                                                                 Animation_input[0][0]
                                                                 Children_input[0][0]
                                                                 Comedy_input[0][0]
                                                                 Crime_input[0][0]
                                                                 Documentary_input[0][0]
                                                                 Drama_input[0][0]
                                                                 Fantasy_input[0][0]
                                                                 Film-Noir_input[0][0]
                                                                 Horror_input[0][0]
                                                                 Musical_input[0][0]
                                                                 Mystery_input[0][0]
                                                                 Romance_input[0][0]
                                                                 Sci-Fi_input[0][0]
                                                                 Thriller_input[0][0]
                                                                 War_input[0][0]
                                                                 Western_input[0][0]
                                                                 age_input[0][0]
                                                                 gender_input[0][0]
                                                                 occupation_input[0][0]
                                                                 ZipCode_input[0][0]
                                                                 Year_input[0][0]
                                                                 Month_input[0][0]
                                                                 Week_input[0][0]
                                                                 Day_input[0][0]
__________________________________________________________________________________________________
Dense (Dense)                   (None, 20)           600         concatenate_6[0][0]
__________________________________________________________________________________________________
Dense_out (Dense)               (None, 1)            21          Dense[0][0]
==================================================================================================
Total params: 621
Trainable params: 621
Non-trainable params: 0
__________________________________________________________________________________________________

In [211]:
model.fit(X_train,y_train,batch_size=512, epochs=100)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).